# Generated by Django 4.1.4 on 2022-12-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskDate',
            field=models.DateField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
