# Generated by Django 4.1.4 on 2023-03-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp01', '0002_task_taskdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskDescription',
            field=models.TextField(blank=True),
        ),
    ]
